DEBUG 2019-10-25 09:21:00.553 UTC: 	 Running on: Linux lxplus602.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-10-25 09:21:00.554 UTC: 	 Executing command: 'submit'
DEBUG 2019-10-25 09:21:00.554 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kaliyana/.crab3
DEBUG 2019-10-25 09:21:00.562 UTC: 	 Checking credentials
DEBUG 2019-10-25 09:21:00.563 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 09:21:00.563 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 09:21:01.669 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 41610

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:02.479 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 41609

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:02.479 UTC: 	 Proxy lifetime 41610 secs is different from voms extension lifetime 41609 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 09:21:02.479 UTC: 	 Proxy valid for 11:33:29 hours
INFO 2019-10-25 09:21:02.479 UTC: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2019-10-25 09:21:02.480 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-10-25 09:21:02.486 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-10-25 09:21:02.613 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:02.613 UTC: 	 Checking credentials
DEBUG 2019-10-25 09:21:02.613 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 09:21:02.613 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 09:21:03.431 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 41608

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:04.248 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 41607

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:04.248 UTC: 	 Proxy lifetime 41608 secs is different from voms extension lifetime 41607 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 09:21:04.248 UTC: 	 Proxy valid for 11:33:27 hours
DEBUG 2019-10-25 09:21:05.163 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u112442 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:05.298 UTC: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
DEBUG 2019-10-25 09:21:05.411 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:05.412 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2019-10-25 09:21:05.412 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage_cmsweb.cern.ch for credential name
DEBUG 2019-10-25 09:21:06.422 UTC: 	 Executing : 
 command : myproxy-info -l f8fea12f46d9be4617ea61f8bc080f9234758131 -s myproxy.cern.ch
 output : username: f8fea12f46d9be4617ea61f8bc080f9234758131
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  timeleft: 363:48:45  (15.2 days)

 error: 
 retcode : 0
DEBUG 2019-10-25 09:21:06.423 UTC: 	 Myproxy is valid: 1309725
DEBUG 2019-10-25 09:21:06.423 UTC: 	 Command use: submit
DEBUG 2019-10-25 09:21:06.423 UTC: 	 Options use: ['-c', 'crabConfig.py']
DEBUG 2019-10-25 09:21:06.506 UTC: 	 CRABClient version: 3.3.1910.patch2
DEBUG 2019-10-25 09:21:06.506 UTC: 	 Instance is prod
DEBUG 2019-10-25 09:21:06.506 UTC: 	 Server base url is cmsweb.cern.ch
DEBUG 2019-10-25 09:21:06.506 UTC: 	 Command url /crabserver/prod/workflow
DEBUG 2019-10-25 09:21:06.506 UTC: 	 Started submission
DEBUG 2019-10-25 09:21:06.506 UTC: 	 Working on /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170
DEBUG 2019-10-25 09:21:06.666 UTC: 	 Loading required information from the environment
DEBUG 2019-10-25 09:21:06.666 UTC: 	 Found CMSSW_10_2_5 for slc6_amd64_gcc700 with base /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5
DEBUG 2019-10-25 09:21:06.666 UTC: 	 Loading required information from the environment
DEBUG 2019-10-25 09:21:06.666 UTC: 	 Found CMSSW_10_2_5 for slc6_amd64_gcc700 with base /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5
DEBUG 2019-10-25 09:21:06.697 UTC: 	 UNIQUE NAME: tarUUID 473edb49-81c5-468c-a186-b60c880a89b7 
DEBUG 2019-10-25 09:21:06.698 UTC: 	 self.config: from WMCore.Configuration import Configuration
config = Configuration()
config.section_('General')
config.General.workArea = 'crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8'
config.General.requestName = 'ana_datamc_qcd120to170'
config.section_('JobType')
config.JobType.psetName = 'histos_crab.py'
config.JobType.pluginName = 'Analysis'
config.section_('Data')
config.Data.inputDataset = '/QCD_Pt_120to170_TuneCP5_13TeV_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM'
config.Data.allowNonValidInputDataset = True
config.Data.totalUnits = -1
config.Data.unitsPerJob = 20
config.Data.ignoreLocality = True
config.Data.inputDBS = 'global'
config.Data.splitting = 'FileBased'
config.Data.outputDatasetTag = 'ana_datamc_qcd120to170'
config.Data.outLFNDirBase = '/store/user/kaliyana'
config.Data.publication = False
config.section_('Site')
config.Site.whitelist = ['T2_US_MIT']
config.Site.storageSite = 'T2_US_MIT'
config.section_('User')
config.section_('Debug')

DEBUG 2019-10-25 09:21:06.698 UTC: 	 self.config.JobType.psetName: histos_crab.py
INFO 2019-10-25 09:21:06.698 UTC: 	 Importing CMSSW configuration histos_crab.py
INFO 2019-10-25 09:21:07.256 UTC: 	 Finished importing CMSSW configuration histos_crab.py
DEBUG 2019-10-25 09:21:07.256 UTC: 	 Writing CMSSW configuration to /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/inputs/PSet.py
DEBUG 2019-10-25 09:21:07.339 UTC: 	 The following EDM output files will be collected: []
DEBUG 2019-10-25 09:21:07.339 UTC: 	 The following TFile output files will be collected: ['zp2mu_histos.root']
DEBUG 2019-10-25 09:21:07.339 UTC: 	 The following user output files (not listed as PoolOuputModule or TFileService in the CMSSW PSet) will be collected: 
DEBUG 2019-10-25 09:21:07.339 UTC: 	 Loading required information from the environment
DEBUG 2019-10-25 09:21:07.339 UTC: 	 Found CMSSW_10_2_5 for slc6_amd64_gcc700 with base /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5
DEBUG 2019-10-25 09:21:07.339 UTC: 	 Making tarball in /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/inputs/473edb49-81c5-468c-a186-b60c880a89b7default.tgz
DEBUG 2019-10-25 09:21:07.341 UTC: 	 Checking directory /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/lib
DEBUG 2019-10-25 09:21:07.341 UTC: 	 Adding directory /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/lib to tarball
DEBUG 2019-10-25 09:21:07.944 UTC: 	 Checking directory /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/biglib
DEBUG 2019-10-25 09:21:07.944 UTC: 	 Adding directory /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/biglib to tarball
DEBUG 2019-10-25 09:21:07.944 UTC: 	 Checking directory /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/module
DEBUG 2019-10-25 09:21:08.161 UTC: 	 Uploading archive /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/inputs/473edb49-81c5-468c-a186-b60c880a89b7default.tgz (1.274414.1 MB) to the CRAB cache. Using URI https://cmsweb.cern.ch/crabcache
DEBUG 2019-10-25 09:21:09.518 UTC: 	 Loading required information from the environment
DEBUG 2019-10-25 09:21:09.518 UTC: 	 Found CMSSW_10_2_5 for slc6_amd64_gcc700 with base /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5
DEBUG 2019-10-25 09:21:09.518 UTC: 	 Making tarball in /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/inputs/debugFiles.tgz
DEBUG 2019-10-25 09:21:09.534 UTC: 	 Uploading archive /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/inputs/debugFiles.tgz (12 KB) to the CRAB cache. Using URI https://cmsweb.cern.ch/crabcache
DEBUG 2019-10-25 09:21:09.614 UTC: 	 Result uploading input files: 009ef9b72c3f6e30cc97f0b18acfe355f68df7ed6c0d51044d72e5bfb68af709.tar.gz 
INFO 2019-10-25 09:21:09.614 UTC: 	 Sending the request to the server at cmsweb.cern.ch
DEBUG 2019-10-25 09:21:09.614 UTC: 	 Submitting {'maxjobruntime': 1250, 'extrajdl': [], 'ignorelocality': 1, 'savelogsflag': 0, 'useparent': 0, 'asyncdest': 'T2_US_MIT', 'algoargs': 20, 'cachefilename': '009ef9b72c3f6e30cc97f0b18acfe355f68df7ed6c0d51044d72e5bfb68af709.tar.gz', 'numcores': 1, 'addoutputfiles': [], 'generator': 'pythia', 'maxmemory': 2000, 'publishdbsurl': 'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', 'priority': 10, 'jobsw': 'CMSSW_10_2_5', 'edmoutfiles': [], 'userfiles': [], 'primarydataset': '', 'inputdata': '/QCD_Pt_120to170_TuneCP5_13TeV_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM', 'lfn': '/store/user/kaliyana', 'dryrun': 0, 'workflow': 'crab_ana_datamc_qcd120to170', 'sitewhitelist': ['T2_US_MIT'], 'nonprodsw': 0, 'tfileoutfiles': ['zp2mu_histos.root'], 'oneEventMode': 0, 'debugfilename': 'c3f1a46cec5a3f873b80da9f9ec5a1a770a75be6ce1b846a98204bb2f88012b6.tar.gz', 'cacheurl': u'https://cmsweb.cern.ch/crabcache', 'saveoutput': 1, 'publication': 0, 'jobarch': 'slc6_amd64_gcc700', 'totalunits': -1, 'splitalgo': 'FileBased', 'ignoreglobalblacklist': 0, 'nonvaliddata': 1, 'dbsurl': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'publishgroupname': 0, 'jobtype': 'Analysis', 'publishname2': 'ana_datamc_qcd120to170'} 
DEBUG 2019-10-25 09:21:09.615 UTC: 	 Encoded submit request: maxjobruntime=1250&ignorelocality=1&savelogsflag=0&useparent=0&asyncdest=T2_US_MIT&algoargs=20&cachefilename=009ef9b72c3f6e30cc97f0b18acfe355f68df7ed6c0d51044d72e5bfb68af709.tar.gz&numcores=1&generator=pythia&maxmemory=2000&publishdbsurl=https%3A%2F%2Fcmsweb.cern.ch%2Fdbs%2Fprod%2Fphys03%2FDBSWriter&priority=10&jobsw=CMSSW_10_2_5&primarydataset=&inputdata=%2FQCD_Pt_120to170_TuneCP5_13TeV_pythia8%2FRunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1%2FMINIAODSIM&lfn=%2Fstore%2Fuser%2Fkaliyana&dryrun=0&workflow=crab_ana_datamc_qcd120to170&nonprodsw=0&oneEventMode=0&debugfilename=c3f1a46cec5a3f873b80da9f9ec5a1a770a75be6ce1b846a98204bb2f88012b6.tar.gz&cacheurl=https%3A%2F%2Fcmsweb.cern.ch%2Fcrabcache&saveoutput=1&publication=0&jobarch=slc6_amd64_gcc700&totalunits=-1&splitalgo=FileBased&ignoreglobalblacklist=0&nonvaliddata=1&dbsurl=https%3A%2F%2Fcmsweb.cern.ch%2Fdbs%2Fprod%2Fglobal%2FDBSReader&publishgroupname=0&jobtype=Analysis&publishname2=ana_datamc_qcd120to170&sitewhitelist=T2_US_MIT&tfileoutfiles=zp2mu_histos.root
DEBUG 2019-10-25 09:21:09.802 UTC: 	 Result: {u'result': [{u'RequestName': u'191025_092109:kaliyana_crab_ana_datamc_qcd120to170'}]}
INFO 2019-10-25 09:21:09.805 UTC: 	 Success: Your task has been delivered to the prod CRAB3 server.
INFO 2019-10-25 09:21:09.806 UTC: 	 Task name: 191025_092109:kaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 09:21:09.806 UTC: 	 Project dir: crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170
INFO 2019-10-25 09:21:09.806 UTC: 	 Please use 'crab status -d crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170' to check how the submission process proceeds.
DEBUG 2019-10-25 09:21:09.806 UTC: 	 About to return
INFO 2019-10-25 09:21:09.809 UTC: 	 Log file is /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/crab.log
DEBUG 2019-10-25 10:44:07.019 UTC: 	 Running on: Linux lxplus602.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-10-25 10:44:07.019 UTC: 	 Executing command: 'status'
DEBUG 2019-10-25 10:44:07.020 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kaliyana/.crab3
DEBUG 2019-10-25 10:44:07.038 UTC: 	 Checking credentials
DEBUG 2019-10-25 10:44:07.041 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 10:44:07.041 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 10:44:08.256 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 36623

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:09.066 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 36622

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:09.067 UTC: 	 Proxy lifetime 36623 secs is different from voms extension lifetime 36622 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 10:44:09.067 UTC: 	 Proxy valid for 10:10:22 hours
DEBUG 2019-10-25 10:44:09.185 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:09.186 UTC: 	 Checking credentials
DEBUG 2019-10-25 10:44:09.188 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 10:44:09.188 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 10:44:09.999 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 36622

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:10.806 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 36621

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:10.806 UTC: 	 Proxy lifetime 36622 secs is different from voms extension lifetime 36621 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 10:44:10.806 UTC: 	 Proxy valid for 10:10:21 hours
DEBUG 2019-10-25 10:44:10.948 UTC: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
DEBUG 2019-10-25 10:44:11.062 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:11.063 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2019-10-25 10:44:11.063 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage_cmsweb.cern.ch for credential name
DEBUG 2019-10-25 10:44:11.671 UTC: 	 Executing : 
 command : myproxy-info -l f8fea12f46d9be4617ea61f8bc080f9234758131 -s myproxy.cern.ch
 output : username: f8fea12f46d9be4617ea61f8bc080f9234758131
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  timeleft: 362:25:40  (15.1 days)

 error: 
 retcode : 0
DEBUG 2019-10-25 10:44:11.672 UTC: 	 Myproxy is valid: 1304740
DEBUG 2019-10-25 10:44:11.673 UTC: 	 Command use: status
DEBUG 2019-10-25 10:44:11.673 UTC: 	 Options use: ['-d', 'crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/']
DEBUG 2019-10-25 10:44:11.779 UTC: 	 CRABClient version: 3.3.1910.patch2
DEBUG 2019-10-25 10:44:11.779 UTC: 	 Instance is prod
DEBUG 2019-10-25 10:44:11.779 UTC: 	 Server base url is cmsweb.cern.ch
DEBUG 2019-10-25 10:44:11.779 UTC: 	 Command url /crabserver/prod/workflow
DEBUG 2019-10-25 10:44:11.924 UTC: 	 Got information from server oracle database: {u'result': [u'191025_092109:kaliyana_crab_ana_datamc_qcd120to170', u'None', u'None', u'SUBMITFAILED', u'SUBMIT', u'2019-10-25 09:21:09.793556', u'None', u'2019-10-25 09:58:04.851294', u'The CRAB server backend was not able to submit the jobs to the Grid schedulers. This could be a temporary glitch. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. The submission was retried 25 times on 5 schedulers. These are the failures per Grid scheduler: {\'crab3@vocms0119.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f12d8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406c050> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406cab8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a758> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406c3b0> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\'], \'crab3@vocms0107.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f1518> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7546076320> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474fd1b8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f1878> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f15a8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\'], \'crab3@vocms0106.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a8c0> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474fdb90> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474d2c68> \\n  File "/data/srv/TaskMan\n[... message truncated to the first 7400 chars ...]', u'CMSSW_10_2_5', u'slc6_amd64_gcc700', u'/QCD_Pt_120to170_TuneCP5_13TeV_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM', u'T', u'0', u"['T2_US_MIT']", u'[]', u'FileBased', u"{'splitOnRun': False, 'halt_job_on_file_boundaries': False, 'files_per_job': 20, 'runs': [], 'lumis': []}", u'009ef9b72c3f6e30cc97f0b18acfe355f68df7ed6c0d51044d72e5bfb68af709.tar.gz', u'https://cmsweb.cern.ch/crabcache', u'kaliyana', u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage', u'cms', u'None', u'None', u'ana_datamc_qcd120to170-00000000000000000000000000000000', u'F', u'T2_US_MIT', u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', u'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', u'F', u'[]', u"['zp2mu_histos.root']", u'[]', u'Analysis', u'pythia', u'None', u'{}', u'[]', u'F', u'crab-prod-tw01', u'[]', u'1250', u'1', u'2000', u'10', u'None', u'[]', u'None', u'None', u'[]', u'[]', u'https://cmsweb.cern.ch/crabserver/prod', u'cmsgwms-collector-global.cern.ch:9620,cmssrv623.fnal.gov:9620', u'crab3@vocms0155.cern.ch', u'F', u'[]', u'T', u'/store/user/kaliyana', u'T', u'None', u'F', u'None', u'QCD_Pt_120to170_TuneCP5_13TeV_pythia8', u'None', u'c3f1a46cec5a3f873b80da9f9ec5a1a770a75be6ce1b846a98204bb2f88012b6.tar.gz', u'None', u'filetransfers', u'F', u'137.138.148.81', u'-1.0', u'None'], u'desc': {u'columns': [u'tm_taskname', u'tm_activity', u'panda_jobset_id', u'tm_task_status', u'tm_task_command', u'tm_start_time', u'tm_start_injection', u'tm_end_injection', u'tm_task_failure', u'tm_job_sw', u'tm_job_arch', u'tm_input_dataset', u'tm_nonvalid_input_dataset', u'tm_use_parent', u'tm_site_whitelist', u'tm_site_blacklist', u'tm_split_algo', u'tm_split_args', u'tm_user_sandbox', u'tm_cache_url', u'tm_username', u'tm_user_dn', u'tm_user_vo', u'tm_user_role', u'tm_user_group', u'tm_publish_name', u'tm_publish_groupname', u'tm_asyncdest', u'tm_dbs_url', u'tm_publish_dbs_url', u'tm_publication', u'tm_outfiles', u'tm_tfile_outfiles', u'tm_edm_outfiles', u'tm_job_type', u'tm_generator', u'tm_events_per_lumi', u'tm_arguments', u'panda_resubmitted_jobs', u'tm_save_logs', u'tw_name', u'tm_user_infiles', u'tm_maxjobruntime', u'tm_numcores', u'tm_maxmemory', u'tm_priority', u'tm_output_dataset', u'tm_task_warnings', u'tm_user_webdir', u'tm_scriptexe', u'tm_scriptargs', u'tm_extrajdl', u'tm_asourl', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'tm_user_files', u'tm_transfer_outputs', u'tm_output_lfn', u'tm_ignore_locality', u'tm_fail_limit', u'tm_one_event_mode', u'tm_secondary_input_dataset', u'tm_primary_dataset', u'tm_last_publication', u'tm_debug_files', u'clusterid', u'tm_asodb', u'tm_ignore_global_blacklist', u'tm_submitter_ip_addr', u'tm_totalunits', u'tm_ddm_reqid']}}
INFO 2019-10-25 10:44:11.925 UTC: 	 CRAB project directory:		/afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170
INFO 2019-10-25 10:44:11.926 UTC: 	 Task name:			191025_092109:kaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 10:44:11.926 UTC: 	 Grid scheduler - Task Worker:	crab3@vocms0155.cern.ch - crab-prod-tw01
INFO 2019-10-25 10:44:11.926 UTC: 	 Status on the CRAB server:	SUBMITFAILED
INFO 2019-10-25 10:44:11.926 UTC: 	 Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/191025_092109%3Akaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 10:44:11.926 UTC: 	 Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=kaliyana&var-task=191025_092109%3Akaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 10:44:11.926 UTC: 	 In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
ERROR 2019-10-25 10:44:11.926 UTC: 	 Failure message from server:	The CRAB server backend was not able to submit the jobs to the Grid schedulers. This could be a temporary glitch. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. The submission was retried 25 times on 5 schedulers. These are the failures per Grid scheduler: {'crab3@vocms0119.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f12d8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406c050> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406cab8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a758> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406c3b0> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\''], 'crab3@vocms0107.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f1518> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7546076320> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474fd1b8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f1878> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f15a8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\''], 'crab3@vocms0106.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a8c0> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474fdb90> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474d2c68> \n  File "/data/srv/TaskMan
				[... message truncated to the first 7400 chars ...]
DEBUG 2019-10-25 10:44:11.927 UTC: 	 The task has not been submitted to the Grid scheduler yet. Not printing job information.
INFO 2019-10-25 10:44:11.938 UTC: 	 Log file is /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/crab.log
DEBUG 2019-10-25 13:15:31.558 UTC: 	 Running on: Linux lxplus602.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-10-25 13:15:31.559 UTC: 	 Executing command: 'status'
DEBUG 2019-10-25 13:15:31.559 UTC: 	 Found CRAB cache file /afs/cern.ch/user/k/kaliyana/.crab3
DEBUG 2019-10-25 13:15:31.569 UTC: 	 Checking credentials
DEBUG 2019-10-25 13:15:31.569 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 13:15:31.569 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 13:15:32.476 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 27539

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:33.286 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 27538

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:33.286 UTC: 	 Proxy lifetime 27539 secs is different from voms extension lifetime 27538 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 13:15:33.286 UTC: 	 Proxy valid for 07:38:58 hours
DEBUG 2019-10-25 13:15:33.560 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:33.560 UTC: 	 Checking credentials
DEBUG 2019-10-25 13:15:33.560 UTC: 	 Found proxy file /tmp/x509up_u112442
DEBUG 2019-10-25 13:15:33.560 UTC: 	 Getting proxy life time left
DEBUG 2019-10-25 13:15:34.567 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -timeleft
 output : 27537

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:35.376 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112442 -actimeleft
 output : 27536

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:35.376 UTC: 	 Proxy lifetime 27537 secs is different from voms extension lifetime 27536 secs for proxy: /tmp/x509up_u112442
DEBUG 2019-10-25 13:15:35.376 UTC: 	 Proxy valid for 07:38:56 hours
DEBUG 2019-10-25 13:15:35.485 UTC: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
DEBUG 2019-10-25 13:15:35.600 UTC: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:35.601 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2019-10-25 13:15:35.601 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage_cmsweb.cern.ch for credential name
DEBUG 2019-10-25 13:15:35.807 UTC: 	 Executing : 
 command : myproxy-info -l f8fea12f46d9be4617ea61f8bc080f9234758131 -s myproxy.cern.ch
 output : username: f8fea12f46d9be4617ea61f8bc080f9234758131
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  timeleft: 359:54:16  (15.0 days)

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:35.809 UTC: 	 Myproxy is valid: 1295656
DEBUG 2019-10-25 13:15:35.914 UTC: 	 Executing : 
 command : openssl x509 -noout -in ~/.globus/usercert.pem -dates
 output : notBefore=Jun 29 15:38:02 2019 GMT
notAfter=Aug  2 15:38:02 2020 GMT

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:35.926 UTC: 	 Delegating a myproxy for 720:00 hours
DEBUG 2019-10-25 13:15:35.926 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage_cmsweb.cern.ch for credential name
DEBUG 2019-10-25 13:15:48.561 UTC: 	 Executing : 
 command : export GT_PROXY_MODE=rfc ; myproxy-init -d -n -s myproxy.cern.ch -x -R '/DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch' -x -Z '/DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch' -l 'f8fea12f46d9be4617ea61f8bc080f9234758131' -t 168:00 -c 720:00
 output : Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage
Creating proxy ................................................. Done
Proxy Verify OK
Your proxy is valid until: Sun Nov 24 14:15:48 2019
A proxy valid for 720 hours (30.0 days) for user f8fea12f46d9be4617ea61f8bc080f9234758131 now exists on myproxy.cern.ch.

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:48.561 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage_cmsweb.cern.ch for credential name
DEBUG 2019-10-25 13:15:49.274 UTC: 	 Executing : 
 command : myproxy-info -l f8fea12f46d9be4617ea61f8bc080f9234758131 -s myproxy.cern.ch
 output : username: f8fea12f46d9be4617ea61f8bc080f9234758131
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(052|058|030|0118|0105|0109).cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod)-tw(02|01).cern.ch
  timeleft: 719:59:59  (30.0 days)

 error: 
 retcode : 0
DEBUG 2019-10-25 13:15:49.274 UTC: 	 My-proxy delegated.
DEBUG 2019-10-25 13:15:49.276 UTC: 	 Command use: status
DEBUG 2019-10-25 13:15:49.276 UTC: 	 Options use: ['-d', 'crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/']
DEBUG 2019-10-25 13:15:49.357 UTC: 	 CRABClient version: 3.3.1910.patch2
DEBUG 2019-10-25 13:15:49.357 UTC: 	 Instance is prod
DEBUG 2019-10-25 13:15:49.357 UTC: 	 Server base url is cmsweb.cern.ch
DEBUG 2019-10-25 13:15:49.357 UTC: 	 Command url /crabserver/prod/workflow
DEBUG 2019-10-25 13:15:49.466 UTC: 	 Got information from server oracle database: {u'result': [u'191025_092109:kaliyana_crab_ana_datamc_qcd120to170', u'None', u'None', u'SUBMITFAILED', u'SUBMIT', u'2019-10-25 09:21:09.793556', u'None', u'2019-10-25 09:58:04.851294', u'The CRAB server backend was not able to submit the jobs to the Grid schedulers. This could be a temporary glitch. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. The submission was retried 25 times on 5 schedulers. These are the failures per Grid scheduler: {\'crab3@vocms0119.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f12d8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406c050> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406cab8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a758> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f751406c3b0> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\'], \'crab3@vocms0107.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f1518> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7546076320> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474fd1b8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f1878> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75464f15a8> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\'], \'crab3@vocms0106.cern.ch\': [u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a8c0> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474fdb90> \\n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\\n    condorIdDict[\\\'ClusterId\\\'] = schedd.submit(dagAd, 1, True, resultAds)\\n\\\'\\\'\', u\'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \\\'Failure when submitting task to scheduler. Error reason: \\\'Trapped exception in Dagman.Fork: <type \\\'exceptions.RuntimeError\\\'> Failed to connect to schedd. <traceback object at 0x7f75474d2c68> \\n  File "/data/srv/TaskMan\n[... message truncated to the first 7400 chars ...]', u'CMSSW_10_2_5', u'slc6_amd64_gcc700', u'/QCD_Pt_120to170_TuneCP5_13TeV_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM', u'T', u'0', u"['T2_US_MIT']", u'[]', u'FileBased', u"{'splitOnRun': False, 'halt_job_on_file_boundaries': False, 'files_per_job': 20, 'runs': [], 'lumis': []}", u'009ef9b72c3f6e30cc97f0b18acfe355f68df7ed6c0d51044d72e5bfb68af709.tar.gz', u'https://cmsweb.cern.ch/crabcache', u'kaliyana', u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kaliyana/CN=821457/CN=Kalpanie Madara Liyanage', u'cms', u'None', u'None', u'ana_datamc_qcd120to170-00000000000000000000000000000000', u'F', u'T2_US_MIT', u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', u'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', u'F', u'[]', u"['zp2mu_histos.root']", u'[]', u'Analysis', u'pythia', u'None', u'{}', u'[]', u'F', u'crab-prod-tw01', u'[]', u'1250', u'1', u'2000', u'10', u'None', u'[]', u'None', u'None', u'[]', u'[]', u'https://cmsweb.cern.ch/crabserver/prod', u'cmsgwms-collector-global.cern.ch:9620,cmssrv623.fnal.gov:9620', u'crab3@vocms0155.cern.ch', u'F', u'[]', u'T', u'/store/user/kaliyana', u'T', u'None', u'F', u'None', u'QCD_Pt_120to170_TuneCP5_13TeV_pythia8', u'None', u'c3f1a46cec5a3f873b80da9f9ec5a1a770a75be6ce1b846a98204bb2f88012b6.tar.gz', u'None', u'filetransfers', u'F', u'137.138.148.81', u'-1.0', u'None'], u'desc': {u'columns': [u'tm_taskname', u'tm_activity', u'panda_jobset_id', u'tm_task_status', u'tm_task_command', u'tm_start_time', u'tm_start_injection', u'tm_end_injection', u'tm_task_failure', u'tm_job_sw', u'tm_job_arch', u'tm_input_dataset', u'tm_nonvalid_input_dataset', u'tm_use_parent', u'tm_site_whitelist', u'tm_site_blacklist', u'tm_split_algo', u'tm_split_args', u'tm_user_sandbox', u'tm_cache_url', u'tm_username', u'tm_user_dn', u'tm_user_vo', u'tm_user_role', u'tm_user_group', u'tm_publish_name', u'tm_publish_groupname', u'tm_asyncdest', u'tm_dbs_url', u'tm_publish_dbs_url', u'tm_publication', u'tm_outfiles', u'tm_tfile_outfiles', u'tm_edm_outfiles', u'tm_job_type', u'tm_generator', u'tm_events_per_lumi', u'tm_arguments', u'panda_resubmitted_jobs', u'tm_save_logs', u'tw_name', u'tm_user_infiles', u'tm_maxjobruntime', u'tm_numcores', u'tm_maxmemory', u'tm_priority', u'tm_output_dataset', u'tm_task_warnings', u'tm_user_webdir', u'tm_scriptexe', u'tm_scriptargs', u'tm_extrajdl', u'tm_asourl', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'tm_user_files', u'tm_transfer_outputs', u'tm_output_lfn', u'tm_ignore_locality', u'tm_fail_limit', u'tm_one_event_mode', u'tm_secondary_input_dataset', u'tm_primary_dataset', u'tm_last_publication', u'tm_debug_files', u'clusterid', u'tm_asodb', u'tm_ignore_global_blacklist', u'tm_submitter_ip_addr', u'tm_totalunits', u'tm_ddm_reqid']}}
INFO 2019-10-25 13:15:49.467 UTC: 	 CRAB project directory:		/afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170
INFO 2019-10-25 13:15:49.467 UTC: 	 Task name:			191025_092109:kaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 13:15:49.467 UTC: 	 Grid scheduler - Task Worker:	crab3@vocms0155.cern.ch - crab-prod-tw01
INFO 2019-10-25 13:15:49.467 UTC: 	 Status on the CRAB server:	SUBMITFAILED
INFO 2019-10-25 13:15:49.468 UTC: 	 Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/191025_092109%3Akaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 13:15:49.468 UTC: 	 Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=kaliyana&var-task=191025_092109%3Akaliyana_crab_ana_datamc_qcd120to170
INFO 2019-10-25 13:15:49.468 UTC: 	 In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
ERROR 2019-10-25 13:15:49.468 UTC: 	 Failure message from server:	The CRAB server backend was not able to submit the jobs to the Grid schedulers. This could be a temporary glitch. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. The submission was retried 25 times on 5 schedulers. These are the failures per Grid scheduler: {'crab3@vocms0119.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f12d8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406c050> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406cab8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a758> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f751406c3b0> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\''], 'crab3@vocms0107.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f1518> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7546076320> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474fd1b8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f1878> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75464f15a8> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\''], 'crab3@vocms0106.cern.ch': [u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f7525b4a8c0> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474fdb90> \n  File "/data/srv/TaskManager/3.3.1909.rc2.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1909.rc2.patch1/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 507, in submitDirect\n    condorIdDict[\'ClusterId\'] = schedd.submit(dagAd, 1, True, resultAds)\n\'\'', u'Failed to submit task 191025_092109:kaliyana_crab_ana_datamc_qcd120to170; \'Failure when submitting task to scheduler. Error reason: \'Trapped exception in Dagman.Fork: <type \'exceptions.RuntimeError\'> Failed to connect to schedd. <traceback object at 0x7f75474d2c68> \n  File "/data/srv/TaskMan
				[... message truncated to the first 7400 chars ...]
DEBUG 2019-10-25 13:15:49.469 UTC: 	 The task has not been submitted to the Grid scheduler yet. Not printing job information.
INFO 2019-10-25 13:15:49.515 UTC: 	 Log file is /afs/cern.ch/user/k/kaliyana/2018Z/CMSSW_10_2_5/src/SUSYBSMAnalysis/Zprime2muAnalysis/test/DataMCSpectraComparison/crab_2017_QCD_Pt_120to170_TuneCP5_13TeV_pythia8/crab_ana_datamc_qcd120to170/crab.log
